apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tasks-prod-hpa
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: openshift-tasks
    apiVersion: v1
    subresource: scale
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetCPUUtilizationPercentage: 80